In [1]:
import pandas as pd         #1
import numpy as np          #2
import seaborn as sns       #3

In [2]:
data=pd.read_csv(r"C:\Users\Lenovo\Desktop\Python\Datasets\banking.csv")

In [3]:
data

Unnamed: 0  age          job  marital  education default  balance  \
0              0   41     services  married    unknown      no     88.0   
1              1   56   technician  married  secondary      no   1938.0   
2              2   30     services   single  secondary      no    245.0   
3              3   34   management   single   tertiary      no   1396.0   
4              4   29   technician   single  secondary      no    -13.0   
...          ...  ...          ...      ...        ...     ...      ...   
5578        5578   27      student   single  secondary      no     91.0   
5579        5579   46  blue-collar  married  secondary      no   1568.0   
5580        5580   39     services  married  secondary      no      0.0   
5581        5579   46  blue-collar  married  secondary      no   1568.0   
5582        5580   39     services  married  secondary      no      0.0   

     housing loan    contact  day month  duration  campaign  pdays  previous  \
0        yes   no   cellular   11   may       105         1    336       2.0   
1         no  yes   cellular   26   feb       229         1    192       4.0   
2         no  yes   cellular    8   jul       187         2     -1       0.0   
3        yes   no   cellular   17   jul       630         1     -1       0.0   
4        yes   no   cellular   14   may       512         3     -1       0.0   
...      ...  ...        ...  ...   ...       ...       ...    ...       ...   
5578      no   no  telephone    4   dec       157         6     95      37.0   
5579     yes   no   cellular    2   jun       310         1     55       6.0   
5580     yes   no   cellular    8   may       503         1     -1       0.0   
5581     yes   no   cellular    2   jun       310         1     55       6.0   
5582     yes   no   cellular    8   may       503         1     -1       0.0   

     poutcome deposit  
0     failure      no  
1     success     yes  
2     unknown      no  
3     unknown      no  
4     unknown      no  
...       ...     ...  
5578    other      no  
5579    other     yes  
5580  unknown      no  
5581    other     yes  
5582  unknown      no  

[5583 rows x 18 columns]


# Data Preprocessing & Feature Engineering

In [4]:
data.isnull().sum()

Unnamed: 0    0
age           0
job           0
marital       0
education     0
default       0
balance       1
housing       0
loan          0
contact       0
day           0
month         0
duration      0
campaign      0
pdays         0
previous      1
poutcome      1
deposit       0
dtype: int64

In [5]:
data.dropna(inplace=True)

In [6]:
data.isnull().sum()

Unnamed: 0    0
age           0
job           0
marital       0
education     0
default       0
balance       0
housing       0
loan          0
contact       0
day           0
month         0
duration      0
campaign      0
pdays         0
previous      0
poutcome      0
deposit       0
dtype: int64

In [7]:
data.head()

Unnamed: 0  age         job  marital  education default  balance housing  \
0           0   41    services  married    unknown      no     88.0     yes   
1           1   56  technician  married  secondary      no   1938.0      no   
2           2   30    services   single  secondary      no    245.0      no   
3           3   34  management   single   tertiary      no   1396.0     yes   
4           4   29  technician   single  secondary      no    -13.0     yes   

  loan   contact  day month  duration  campaign  pdays  previous poutcome  \
0   no  cellular   11   may       105         1    336       2.0  failure   
1  yes  cellular   26   feb       229         1    192       4.0  success   
2  yes  cellular    8   jul       187         2     -1       0.0  unknown   
3   no  cellular   17   jul       630         1     -1       0.0  unknown   
4   no  cellular   14   may       512         3     -1       0.0  unknown   

  deposit  
0      no  
1     yes  
2      no  
3      no  
4      no

In [8]:
from sklearn.preprocessing import LabelEncoder            #4
l=LabelEncoder()
data["job"]=l.fit_transform(data["job"])
data["marital"]=l.fit_transform(data["marital"])
data["education"]=l.fit_transform(data["education"])
data["default"]=l.fit_transform(data["default"])
data["housing"]=l.fit_transform(data["housing"])
data["loan"]=l.fit_transform(data["loan"])
data["contact"]=l.fit_transform(data["contact"])
data["month"]=l.fit_transform(data["month"])
data["poutcome"]=l.fit_transform(data["poutcome"])
data["deposit"]=l.fit_transform(data["deposit"])

In [9]:
data.head()

Unnamed: 0  age  job  marital  education  default  balance  housing  loan  \
0           0   41    7        1          3        0     88.0        1     0   
1           1   56    9        1          1        0   1938.0        0     1   
2           2   30    7        2          1        0    245.0        0     1   
3           3   34    4        2          2        0   1396.0        1     0   
4           4   29    9        2          1        0    -13.0        1     0   

   contact  day  month  duration  campaign  pdays  previous  poutcome  deposit  
0        0   11      8       105         1    336       2.0         0        0  
1        0   26      3       229         1    192       4.0         2        1  
2        0    8      5       187         2     -1       0.0         3        0  
3        0   17      5       630         1     -1       0.0         3        0  
4        0   14      8       512         3     -1       0.0         3        0

In [10]:
x=data.iloc[:,:-1].values
y=data.iloc[:,-1].values

In [11]:
data["deposit"].value_counts()

0    2958
1    2622
Name: deposit, dtype: int64

# Feature Scaling 

In [12]:
from sklearn.preprocessing import StandardScaler                       #5
sc=StandardScaler()
Sc=sc.fit(x)
Scaler_data=sc.transform(x)

In [13]:
Scaler_data

array([[-1.73346982, -0.01406746,  0.79773447, ...,  2.55932401,
         0.49687631, -2.43029246],
       [-1.73284905,  1.24388803,  1.42384858, ...,  1.25910251,
         1.36168288, -0.45763526],
       [-1.73222828, -0.93656815,  0.79773447, ..., -0.48355547,
        -0.36793025,  0.52869334],
       ...,
       [ 1.73043472, -0.18179486,  0.79773447, ..., -0.48355547,
        -0.36793025,  0.52869334],
       [ 1.72981395,  0.40525104, -1.08060789, ...,  0.02208622,
         2.22648944, -1.44396386],
       [ 1.73043472, -0.18179486,  0.79773447, ..., -0.48355547,
        -0.36793025,  0.52869334]])

In [14]:
dataset=pd.DataFrame(Scaler_data)

In [15]:
dataset

0         1         2         3         4         5         6   \
0    -1.733470 -0.014067  0.797734 -0.338330  2.284442 -0.123628 -0.436753   
1    -1.732849  1.243888  1.423849 -0.338330 -0.386804 -0.123628  0.129618   
2    -1.732228 -0.936568  0.797734  1.256163 -0.386804 -0.123628 -0.388688   
3    -1.731608 -0.601113 -0.141437  1.256163  0.948819 -0.123628 -0.036313   
4    -1.730987 -1.020432  1.423849  1.256163 -0.386804 -0.123628 -0.467674   
...        ...       ...       ...       ...       ...       ...       ...   
5575  1.729193 -1.188159  1.110792  1.256163 -0.386804 -0.123628 -0.435835   
5576  1.729814  0.405251 -1.080608 -0.338330 -0.386804 -0.123628  0.016344   
5577  1.730435 -0.181795  0.797734 -0.338330 -0.386804 -0.123628 -0.463694   
5578  1.729814  0.405251 -1.080608 -0.338330 -0.386804 -0.123628  0.016344   
5579  1.730435 -0.181795  0.797734 -0.338330 -0.386804 -0.123628 -0.463694   

            7         8         9         10        11        12        13  \
0     1.050371 -0.384286 -0.591429 -0.554435  0.796720 -0.765033 -0.543753   
1    -0.952045  2.602227 -0.591429  1.218284 -0.772091 -0.404681 -0.543753   
2    -0.952045  2.602227 -0.591429 -0.908979 -0.144567 -0.526736 -0.182675   
3     1.050371 -0.384286 -0.591429  0.154652 -0.144567  0.760647 -0.543753   
4     1.050371 -0.384286 -0.591429 -0.199892  0.796720  0.417733  0.178404   
...        ...       ...       ...       ...       ...       ...       ...   
5575 -0.952045 -0.384286  0.636771 -1.381704 -1.085853 -0.613918  1.261638   
5576  1.050371 -0.384286 -0.591429 -1.618067  0.169195 -0.169291 -0.543753   
5577  1.050371 -0.384286 -0.591429 -0.908979  0.796720  0.391578 -0.543753   
5578  1.050371 -0.384286 -0.591429 -1.618067  0.169195 -0.169291 -0.543753   
5579  1.050371 -0.384286 -0.591429 -0.908979  0.796720  0.391578 -0.543753   

            14         15        16  
0     2.559324   0.496876 -2.430292  
1     1.259103   1.361683 -0.457635  
2    -0.483555  -0.367930  0.528693  
3    -0.483555  -0.367930  0.528693  
4    -0.483555  -0.367930  0.528693  
...        ...        ...       ...  
5575  0.383259  15.630991 -1.443964  
5576  0.022086   2.226489 -1.443964  
5577 -0.483555  -0.367930  0.528693  
5578  0.022086   2.226489 -1.443964  
5579 -0.483555  -0.367930  0.528693  

[5580 rows x 17 columns]

# Data spliting 

In [16]:
X1=dataset
y1=data.iloc[:,-1].values

# Data Imbalancing

In [17]:
from imblearn.over_sampling import RandomOverSampler         #6

In [18]:
r=RandomOverSampler()
x_data,y_data=r.fit_resample(X1,y1)

In [19]:
from collections import Counter                              #7

In [20]:
print(Counter(y_data))

Counter({0: 2958, 1: 2958})


In [21]:
from sklearn.model_selection import train_test_split                 #8

In [22]:
x_train,x_test,y_train,y_test=train_test_split(x_data,y_data,test_size=0.2,random_state=20)

In [23]:
from collections import Counter                                  #9

In [24]:
print(Counter(y_train))

Counter({1: 2372, 0: 2360})


In [25]:
print(Counter(y_test))

Counter({0: 598, 1: 586})


# Logistic Regression

In [26]:
from sklearn.metrics import accuracy_score                  #10

In [27]:
from sklearn.linear_model import LogisticRegression            #11
l1=LogisticRegression()
l1.fit(x_train,y_train)

y_pred1=l1.predict(x_test)
print(y_pred1)

ac1=accuracy_score(y_test,y_pred1)*100
print("logistic_regression",ac1)

[1 1 1 ... 0 1 1]
logistic_regression 78.04054054054053


# KNeighbors Classifier

In [28]:
from sklearn.neighbors import KNeighborsClassifier                   #12
k=KNeighborsClassifier(n_neighbors=5)
k.fit(x_train,y_train)

y_pred2=k.predict(x_test)
print(y_pred2)

ac2=accuracy_score(y_test,y_pred2)*100
print("KNN_Accuracy: ",ac2)

[0 1 1 ... 1 1 1]
KNN_Accuracy:  74.32432432432432


In [29]:
from sklearn.svm import SVC                               #13

s=SVC()
s.fit(x_train,y_train)

y_pred3=s.predict(x_test)
print(y_pred3)

ac3=accuracy_score(y_test,y_pred3)*100
print("SVM accuracy: ",ac3)

[1 1 1 ... 1 1 1]
SVM accuracy:  81.33445945945947


# Model imbalancing

In [30]:
from sklearn.model_selection import cross_val_score               #14
from sklearn.model_selection import cross_val_predict             #15


## KFold

In [31]:
from sklearn.model_selection import KFold                            #16

In [32]:
kf=KFold(n_splits=5,shuffle=True)
kf.get_n_splits(x)
print(kf)

sc=cross_val_score(l1,x_train,y_train,cv=kf)
print(sc)
y_pred4=cross_val_predict(l1,x_test,y_test)
print(y_pred4)

ac4=accuracy_score(y_test,y_pred4)*100
print("Cross_Val & Logistic: ",ac4)

KFold(n_splits=5, random_state=None, shuffle=True)
[0.78141499 0.78775079 0.79809725 0.80549683 0.76744186]
[1 1 1 ... 0 1 1]
Cross_Val & Logistic:  78.80067567567568


In [33]:

kf=KFold(n_splits=5,shuffle=True)
kf.get_n_splits(x)
print(kf)

sc=cross_val_score(k,x_train,y_train,cv=kf)
print(sc)
y_pred5=cross_val_predict(k,x_test,y_test)
print(y_pred5)

ac5=accuracy_score(y_test,y_pred5)*100
print("Cross_Val & KNN: ",ac5)

KFold(n_splits=5, random_state=None, shuffle=True)
[0.75079197 0.7687434  0.74524313 0.75687104 0.72938689]
[1 0 1 ... 0 1 1]
Cross_Val & KNN:  71.0304054054054


In [34]:
kf=KFold(n_splits=5,shuffle=True)
kf.get_n_splits(x)
print(kf)

sc=cross_val_score(s,x_train,y_train,cv=kf)
print(sc)
y_pred6=cross_val_predict(s,x_test,y_test)
print(y_pred6)

ac6=accuracy_score(y_test,y_pred6)*100
print("Cross_Val & SVM: ",ac6)

KFold(n_splits=5, random_state=None, shuffle=True)
[0.82259768 0.80042239 0.81606765 0.83192389 0.79704017]
[1 0 1 ... 1 1 1]
Cross_Val & SVM:  80.15202702702703


## Stratified KFold

In [35]:
from sklearn.model_selection import StratifiedKFold             #17

In [36]:
skf=StratifiedKFold(n_splits=5,shuffle=True)
skf.get_n_splits(x_train,y_train)
skf

sc1=cross_val_score(l1,x_train,y_train,cv=skf)
y_pred7=cross_val_predict(l1,x_test,y_test)
print(y_pred7)

print(np.mean(sc1)*100)

ac7=accuracy_score(y_pred7,y_test)*100
print("Accuracy Of Logistic With Stratified KFold",ac7)

[1 1 1 ... 0 1 1]
79.05708691740469
Accuracy Of Logistic With Stratified KFold 78.80067567567568


In [37]:
skf=StratifiedKFold(n_splits=5,shuffle=True)
skf.get_n_splits(x_train,y_train)
skf

sc2=cross_val_score(k,x_train,y_train,cv=skf)
y_pred8=cross_val_predict(k,x_test,y_test)
print(y_pred8)

print(np.mean(sc2)*100)

ac8=accuracy_score(y_pred8,y_test)*100
print("Accuracy Of KNeighbors With Stratified KFold",ac8)

[1 0 1 ... 0 1 1]
74.40824591287497
Accuracy Of KNeighbors With Stratified KFold 71.0304054054054


In [38]:
skf=StratifiedKFold(n_splits=5,shuffle=True)
skf.get_n_splits(x_train,y_train)
skf

sc3=cross_val_score(s,x_train,y_train,cv=skf)
y_pred9=cross_val_predict(s,x_test,y_test)
print(y_pred9)

print(np.mean(sc3)*100)

ac9=accuracy_score(y_pred9,y_test)*100
print("Accuracy Of SVM With Stratified KFold",ac9)

[1 0 1 ... 1 1 1]
81.1077822253874
Accuracy Of SVM With Stratified KFold 80.15202702702703


# Ensemble Technique

## Voting Classifier

In [39]:
from sklearn.ensemble import VotingClassifier           #18

In [40]:
maxvote=VotingClassifier(estimators=[("logistic",l1),("KNN",k),("SVM",s)])
maxvote.fit(x_train,y_train)
y_mv=maxvote.predict(x_test)
print(y_mv)


ac10=accuracy_score(y_mv,y_test)*100
print(ac10)

[1 1 1 ... 1 1 1]
80.48986486486487


## Bagging Classifier  with logistic

In [41]:
from sklearn.ensemble import BaggingClassifier       #19
bg=BaggingClassifier(n_estimators=5,base_estimator=l1) 
bg.fit(x_train,y_train)
y_bg=bg.predict(x_test)
print(y_bg)

ac11=accuracy_score(y_bg,y_test)*100

print("Accuracy_score Bagging classifier",ac11)

[1 1 1 ... 0 1 1]
Accuracy_score Bagging classifier 78.37837837837837


## Bagging Classifier with KNN

In [42]:
from sklearn.ensemble import BaggingClassifier       
bg=BaggingClassifier(n_estimators=5,base_estimator=k) 
bg.fit(x_train,y_train)
y_bg1=bg.predict(x_test)
print(y_bg1)

ac12=accuracy_score(y_bg1,y_test)*100

print("Accuracy_score Bagging classifier",ac12)

[0 1 1 ... 1 1 1]
Accuracy_score Bagging classifier 75.4222972972973


# Bagging Classifier with SVM

In [43]:
from sklearn.ensemble import BaggingClassifier       
bg=BaggingClassifier(n_estimators=5,base_estimator=s) 
bg.fit(x_train,y_train)
y_bg2=bg.predict(x_test)
print(y_bg)

ac13=accuracy_score(y_bg2,y_test)*100

print("Accuracy_score Bagging classifier",ac13)

[1 1 1 ... 0 1 1]
Accuracy_score Bagging classifier 81.6722972972973


# Confusion_Matrix

In [44]:
from sklearn.metrics import confusion_matrix      #20

In [45]:
cm=confusion_matrix(y_bg2,y_test)
print(cm)

[[479  98]
 [119 488]]
